#!/bin/sh
if [[ ! -e $1 ]]; then
    echo "error: there is no '$1' directory"
    exit 1
fi

cd $1

rm result > /dev/null 2>&1
TEST_VCDIFF=1 /bin/sh -c 'time ../../vcdiff *.vcd > result'
diff result gold > /dev/null
if [ $? == 0 ]; then
    echo PASSED
else
    echo FAILED
fi

cd ..
